version: "3"

services:
  vscode_angular:
    container_name: vscode_angular
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "4201:4201"
